### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#1373]
Souffle can be built on Windows, but currently we don't actually test on Windows so this could accidentally change. Adding Windows to the CI would be helpful.

We currently use Travis CI which has Windows support, so that may be the easiest route. Adding it is just a case of modifying .travis.yml to add something like
```
  - stage: Testing
    os: windows
    language: cpp
    env:
    - "msvc non-eval"
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance SOUFFLE_CONFS="-j8,-c -j8"
    before_script:
    -  <path to init script if needed>
    script:
    - <path to run tests>
```
